"""empty message

Revision ID: 25742a5c6ced
Revises: 1c726d98d424
Create Date: 2023-10-31 14:14:59.722237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25742a5c6ced'
down_revision = '1c726d98d424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_table')
    # ### end Alembic commands ###
