"""empty message

Revision ID: c125c63aba4b
Revises: a1f6507a05e0
Create Date: 2023-11-03 12:08:53.037385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c125c63aba4b'
down_revision = 'a1f6507a05e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_table', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
